/* AUTO-GENERATED by scripts/stripe-sync-live.mjs — do not edit by hand */
export type StripeCatalogEntry = {
  productId: string;
  monthlyPriceId: string;
  yearlyPriceId: string;
  monthlyCents: number;
  yearlyCents: number;
};

export const STRIPE_CATALOG = {
  "solo": {
    "productId": "prod_Uw3ATOQS0hVSPD",
    "monthlyPriceId": "price_1TwB4XHUdx34FiQGBU3mm0gn",
    "yearlyPriceId": "price_1TwB4YHUdx34FiQGwlXiF20r",
    "monthlyCents": 2900,
    "yearlyCents": 29000
  },
  "business": {
    "productId": "prod_Uw3AznrGZNbTER",
    "monthlyPriceId": "price_1TwB4ZHUdx34FiQGvagAT9ja",
    "yearlyPriceId": "price_1TwB4aHUdx34FiQGhMuITUsB",
    "monthlyCents": 8900,
    "yearlyCents": 89000
  },
  "growth": {
    "productId": "prod_Uw3A4ZiHeEgPxZ",
    "monthlyPriceId": "price_1TwB4bHUdx34FiQGAMPA5aia",
    "yearlyPriceId": "price_1TwB4cHUdx34FiQGDiR5HxSn",
    "monthlyCents": 14900,
    "yearlyCents": 149000
  },
  "autopilot": {
    "productId": "prod_Uw3A8vkwW46v2M",
    "monthlyPriceId": "price_1TwB4dHUdx34FiQG4Ytdk8Pj",
    "yearlyPriceId": "price_1TwB4dHUdx34FiQGr4dFay6K",
    "monthlyCents": 24900,
    "yearlyCents": 249000
  },
  "agency_start": {
    "productId": "prod_Uw3BucTMlcu1Kn",
    "monthlyPriceId": "price_1TwB4fHUdx34FiQGzjT1Visz",
    "yearlyPriceId": "price_1TwB4fHUdx34FiQGXdRhXpkV",
    "monthlyCents": 12900,
    "yearlyCents": 129000
  },
  "agency_growth": {
    "productId": "prod_Uw3B4aUFXhFs22",
    "monthlyPriceId": "price_1TwB4gHUdx34FiQGeAmEuQ1C",
    "yearlyPriceId": "price_1TwB4hHUdx34FiQGWu7I8Ig0",
    "monthlyCents": 29900,
    "yearlyCents": 299000
  },
  "agency_scale": {
    "productId": "prod_Uw3BEvQBKTU5oY",
    "monthlyPriceId": "price_1TwB4iHUdx34FiQG3aGFFtav",
    "yearlyPriceId": "price_1TwB4jHUdx34FiQGDq5w2dty",
    "monthlyCents": 59900,
    "yearlyCents": 599000
  },
  "enterprise": {
    "productId": "prod_Uw3BVFvcXSeEuU",
    "monthlyPriceId": "price_1TwB4kHUdx34FiQGugWTTiXX",
    "yearlyPriceId": "price_1TwB4lHUdx34FiQGAeJm2YAe",
    "monthlyCents": 99900,
    "yearlyCents": 999000
  }
} as const satisfies Record<string, StripeCatalogEntry>;

export const STRIPE_PRICE_TO_PLAN: Record<string, { planId: string; interval: "month" | "year" }> = {
  "price_1TwB4XHUdx34FiQGBU3mm0gn": { planId: "solo", interval: "month" },
  "price_1TwB4YHUdx34FiQGwlXiF20r": { planId: "solo", interval: "year" },
  "price_1TwB4ZHUdx34FiQGvagAT9ja": { planId: "business", interval: "month" },
  "price_1TwB4aHUdx34FiQGhMuITUsB": { planId: "business", interval: "year" },
  "price_1TwB4bHUdx34FiQGAMPA5aia": { planId: "growth", interval: "month" },
  "price_1TwB4cHUdx34FiQGDiR5HxSn": { planId: "growth", interval: "year" },
  "price_1TwB4dHUdx34FiQG4Ytdk8Pj": { planId: "autopilot", interval: "month" },
  "price_1TwB4dHUdx34FiQGr4dFay6K": { planId: "autopilot", interval: "year" },
  "price_1TwB4fHUdx34FiQGzjT1Visz": { planId: "agency_start", interval: "month" },
  "price_1TwB4fHUdx34FiQGXdRhXpkV": { planId: "agency_start", interval: "year" },
  "price_1TwB4gHUdx34FiQGeAmEuQ1C": { planId: "agency_growth", interval: "month" },
  "price_1TwB4hHUdx34FiQGWu7I8Ig0": { planId: "agency_growth", interval: "year" },
  "price_1TwB4iHUdx34FiQG3aGFFtav": { planId: "agency_scale", interval: "month" },
  "price_1TwB4jHUdx34FiQGDq5w2dty": { planId: "agency_scale", interval: "year" },
  "price_1TwB4kHUdx34FiQGugWTTiXX": { planId: "enterprise", interval: "month" },
  "price_1TwB4lHUdx34FiQGAeJm2YAe": { planId: "enterprise", interval: "year" },
};
