/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingAccountsRouteImport } from './routes/onboarding.accounts'
import { Route as OnboardingAuditRouteImport } from './routes/onboarding.audit'
import { Route as OnboardingBrandRouteImport } from './routes/onboarding.brand'
import { Route as OnboardingBudgetRouteImport } from './routes/onboarding.budget'
import { Route as OnboardingBusinessRouteImport } from './routes/onboarding.business'
import { Route as OnboardingConnectRouteImport } from './routes/onboarding.connect'
import { Route as OnboardingControlRouteImport } from './routes/onboarding.control'
import { Route as OnboardingGoalRouteImport } from './routes/onboarding.goal'
import { Route as OnboardingSummaryRouteImport } from './routes/onboarding.summary'
import { Route as PlateformesIndexRouteImport } from './routes/plateformes.index'
import { Route as PlateformesSlugRouteImport } from './routes/plateformes.$slug'
import { Route as SecteursIndexRouteImport } from './routes/secteurs.index'
import { Route as SecteursSlugRouteImport } from './routes/secteurs.$slug'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as AdminAdminActionsRouteImport } from './routes/_admin/admin.actions'
import { Route as AdminAdminApprovalsRouteImport } from './routes/_admin/admin.approvals'
import { Route as AdminAdminAuditRouteImport } from './routes/_admin/admin.audit'
import { Route as AdminAdminBillingRouteImport } from './routes/_admin/admin.billing'
import { Route as AdminAdminBookingRouteImport } from './routes/_admin/admin.booking'
import { Route as AdminAdminComplianceRouteImport } from './routes/_admin/admin.compliance'
import { Route as AdminAdminConnectionsRouteImport } from './routes/_admin/admin.connections'
import { Route as AdminAdminCostsRouteImport } from './routes/_admin/admin.costs'
import { Route as AdminAdminFinanceRouteImport } from './routes/_admin/admin.finance'
import { Route as AdminAdminFlagsRouteImport } from './routes/_admin/admin.flags'
import { Route as AdminAdminIncidentsRouteImport } from './routes/_admin/admin.incidents'
import { Route as AdminAdminMcpRouteImport } from './routes/_admin/admin.mcp'
import { Route as AdminAdminOrganizationsRouteImport } from './routes/_admin/admin.organizations'
import { Route as AdminAdminPoliciesRouteImport } from './routes/_admin/admin.policies'
import { Route as AdminAdminProductAnalyticsRouteImport } from './routes/_admin/admin.product-analytics'
import { Route as AdminAdminPromptsRouteImport } from './routes/_admin/admin.prompts'
import { Route as AdminAdminRolesRouteImport } from './routes/_admin/admin.roles'
import { Route as AdminAdminRunsRouteImport } from './routes/_admin/admin.runs'
import { Route as AdminAdminSecurityRouteImport } from './routes/_admin/admin.security'
import { Route as AdminAdminSupportRouteImport } from './routes/_admin/admin.support'
import { Route as AdminAdminSystemRouteImport } from './routes/_admin/admin.system'
import { Route as AdminAdminTemplatesRouteImport } from './routes/_admin/admin.templates'
import { Route as AdminAdminUsageRouteImport } from './routes/_admin/admin.usage'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin.users'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppAgencyRouteImport } from './routes/_authenticated/app.agency'
import { Route as AuthenticatedAppAuditRouteImport } from './routes/_authenticated/app.audit'
import { Route as AuthenticatedAppAutomationsRouteImport } from './routes/_authenticated/app.automations'
import { Route as AuthenticatedAppCampaignsRouteImport } from './routes/_authenticated/app.campaigns'
import { Route as AuthenticatedAppConnectionsRouteImport } from './routes/_authenticated/app.connections'
import { Route as AuthenticatedAppCreationsRouteImport } from './routes/_authenticated/app.creations'
import { Route as AuthenticatedAppLeadsRouteImport } from './routes/_authenticated/app.leads'
import { Route as AuthenticatedAppMcpRouteImport } from './routes/_authenticated/app.mcp'
import { Route as AuthenticatedAppOrkestriaRouteImport } from './routes/_authenticated/app.orkestria'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppRoadmapRouteImport } from './routes/_authenticated/app.roadmap'
import { Route as AuthenticatedAppRunsRouteImport } from './routes/_authenticated/app.runs'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronAutonomyRouteImport } from './routes/api/cron/autonomy'
import { Route as ApiMcpIndexRouteImport } from './routes/api/mcp/index'
import { Route as ApiMcpCallRouteImport } from './routes/api/mcp/call'
import { Route as ApiMcpToolsRouteImport } from './routes/api/mcp/tools'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as PubliciteSectorCityRouteImport } from './routes/publicite.$sector.$city'
import { Route as AdminAdminConnectionsIdRouteImport } from './routes/_admin/admin.connections.$id'
import { Route as AdminAdminOrganizationsIdRouteImport } from './routes/_admin/admin.organizations.$id'
import { Route as AdminAdminRunsIdRouteImport } from './routes/_admin/admin.runs.$id'
import { Route as AuthenticatedAppCampaignsIndexRouteImport } from './routes/_authenticated/app.campaigns.index'
import { Route as AuthenticatedAppCampaignsIdRouteImport } from './routes/_authenticated/app.campaigns.$id'
import { Route as AuthenticatedAppCampaignsNewRouteImport } from './routes/_authenticated/app.campaigns.new'
import { Route as AuthenticatedAppRunsIdRouteImport } from './routes/_authenticated/app.runs.$id'
import { Route as ApiOauthConnectorAuthorizeRouteImport } from './routes/api/oauth/$connector.authorize'
import { Route as ApiOauthConnectorCallbackRouteImport } from './routes/api/oauth/$connector.callback'
import { Route as ApiRunsIdStreamRouteImport } from './routes/api/runs/$id.stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAccountsRoute = OnboardingAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingAuditRoute = OnboardingAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingBrandRoute = OnboardingBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingBudgetRoute = OnboardingBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingBusinessRoute = OnboardingBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingConnectRoute = OnboardingConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingControlRoute = OnboardingControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingGoalRoute = OnboardingGoalRouteImport.update({
  id: '/goal',
  path: '/goal',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingSummaryRoute = OnboardingSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => OnboardingRoute,
} as any)
const PlateformesIndexRoute = PlateformesIndexRouteImport.update({
  id: '/plateformes/',
  path: '/plateformes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlateformesSlugRoute = PlateformesSlugRouteImport.update({
  id: '/plateformes/$slug',
  path: '/plateformes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SecteursIndexRoute = SecteursIndexRouteImport.update({
  id: '/secteurs/',
  path: '/secteurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecteursSlugRoute = SecteursSlugRouteImport.update({
  id: '/secteurs/$slug',
  path: '/secteurs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminActionsRoute = AdminAdminActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminApprovalsRoute = AdminAdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditRoute = AdminAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminBillingRoute = AdminAdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminBookingRoute = AdminAdminBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminComplianceRoute = AdminAdminComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminConnectionsRoute = AdminAdminConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCostsRoute = AdminAdminCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFinanceRoute = AdminAdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFlagsRoute = AdminAdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminIncidentsRoute = AdminAdminIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminMcpRoute = AdminAdminMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminOrganizationsRoute = AdminAdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPoliciesRoute = AdminAdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminProductAnalyticsRoute =
  AdminAdminProductAnalyticsRouteImport.update({
    id: '/product-analytics',
    path: '/product-analytics',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminPromptsRoute = AdminAdminPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRolesRoute = AdminAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminRunsRoute = AdminAdminRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSecurityRoute = AdminAdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSupportRoute = AdminAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSystemRoute = AdminAdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTemplatesRoute = AdminAdminTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUsageRoute = AdminAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAgencyRoute = AuthenticatedAppAgencyRouteImport.update({
  id: '/agency',
  path: '/agency',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAuditRoute = AuthenticatedAppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAutomationsRoute =
  AuthenticatedAppAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCampaignsRoute =
  AuthenticatedAppCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConnectionsRoute =
  AuthenticatedAppConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCreationsRoute =
  AuthenticatedAppCreationsRouteImport.update({
    id: '/creations',
    path: '/creations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeadsRoute = AuthenticatedAppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMcpRoute = AuthenticatedAppMcpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOrkestriaRoute =
  AuthenticatedAppOrkestriaRouteImport.update({
    id: '/orkestria',
    path: '/orkestria',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRoadmapRoute = AuthenticatedAppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRunsRoute = AuthenticatedAppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronAutonomyRoute = ApiCronAutonomyRouteImport.update({
  id: '/api/cron/autonomy',
  path: '/api/cron/autonomy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpIndexRoute = ApiMcpIndexRouteImport.update({
  id: '/api/mcp/',
  path: '/api/mcp/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpCallRoute = ApiMcpCallRouteImport.update({
  id: '/api/mcp/call',
  path: '/api/mcp/call',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpToolsRoute = ApiMcpToolsRouteImport.update({
  id: '/api/mcp/tools',
  path: '/api/mcp/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const PubliciteSectorCityRoute = PubliciteSectorCityRouteImport.update({
  id: '/publicite/$sector/$city',
  path: '/publicite/$sector/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminConnectionsIdRoute = AdminAdminConnectionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminConnectionsRoute,
} as any)
const AdminAdminOrganizationsIdRoute =
  AdminAdminOrganizationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AdminAdminOrganizationsRoute,
  } as any)
const AdminAdminRunsIdRoute = AdminAdminRunsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminAdminRunsRoute,
} as any)
const AuthenticatedAppCampaignsIndexRoute =
  AuthenticatedAppCampaignsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppCampaignsRoute,
  } as any)
const AuthenticatedAppCampaignsIdRoute =
  AuthenticatedAppCampaignsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppCampaignsRoute,
  } as any)
const AuthenticatedAppCampaignsNewRoute =
  AuthenticatedAppCampaignsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAppCampaignsRoute,
  } as any)
const AuthenticatedAppRunsIdRoute = AuthenticatedAppRunsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAppRunsRoute,
} as any)
const ApiOauthConnectorAuthorizeRoute =
  ApiOauthConnectorAuthorizeRouteImport.update({
    id: '/api/oauth/$connector/authorize',
    path: '/api/oauth/$connector/authorize',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOauthConnectorCallbackRoute =
  ApiOauthConnectorCallbackRouteImport.update({
    id: '/api/oauth/$connector/callback',
    path: '/api/oauth/$connector/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRunsIdStreamRoute = ApiRunsIdStreamRouteImport.update({
  id: '/api/runs/$id/stream',
  path: '/api/runs/$id/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding/accounts': typeof OnboardingAccountsRoute
  '/onboarding/audit': typeof OnboardingAuditRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/budget': typeof OnboardingBudgetRoute
  '/onboarding/business': typeof OnboardingBusinessRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/control': typeof OnboardingControlRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/summary': typeof OnboardingSummaryRoute
  '/plateformes/$slug': typeof PlateformesSlugRoute
  '/secteurs/$slug': typeof SecteursSlugRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/plateformes/': typeof PlateformesIndexRoute
  '/secteurs/': typeof SecteursIndexRoute
  '/admin/actions': typeof AdminAdminActionsRoute
  '/admin/approvals': typeof AdminAdminApprovalsRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/billing': typeof AdminAdminBillingRoute
  '/admin/booking': typeof AdminAdminBookingRoute
  '/admin/compliance': typeof AdminAdminComplianceRoute
  '/admin/connections': typeof AdminAdminConnectionsRouteWithChildren
  '/admin/costs': typeof AdminAdminCostsRoute
  '/admin/finance': typeof AdminAdminFinanceRoute
  '/admin/flags': typeof AdminAdminFlagsRoute
  '/admin/incidents': typeof AdminAdminIncidentsRoute
  '/admin/mcp': typeof AdminAdminMcpRoute
  '/admin/organizations': typeof AdminAdminOrganizationsRouteWithChildren
  '/admin/policies': typeof AdminAdminPoliciesRoute
  '/admin/product-analytics': typeof AdminAdminProductAnalyticsRoute
  '/admin/prompts': typeof AdminAdminPromptsRoute
  '/admin/roles': typeof AdminAdminRolesRoute
  '/admin/runs': typeof AdminAdminRunsRouteWithChildren
  '/admin/security': typeof AdminAdminSecurityRoute
  '/admin/support': typeof AdminAdminSupportRoute
  '/admin/system': typeof AdminAdminSystemRoute
  '/admin/templates': typeof AdminAdminTemplatesRoute
  '/admin/usage': typeof AdminAdminUsageRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/app/agency': typeof AuthenticatedAppAgencyRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/automations': typeof AuthenticatedAppAutomationsRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsRouteWithChildren
  '/app/connections': typeof AuthenticatedAppConnectionsRoute
  '/app/creations': typeof AuthenticatedAppCreationsRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/mcp': typeof AuthenticatedAppMcpRoute
  '/app/orkestria': typeof AuthenticatedAppOrkestriaRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/roadmap': typeof AuthenticatedAppRoadmapRoute
  '/app/runs': typeof AuthenticatedAppRunsRouteWithChildren
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/autonomy': typeof ApiCronAutonomyRoute
  '/api/mcp/call': typeof ApiMcpCallRoute
  '/api/mcp/tools': typeof ApiMcpToolsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/publicite/$sector/$city': typeof PubliciteSectorCityRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/api/mcp/': typeof ApiMcpIndexRoute
  '/admin/connections/$id': typeof AdminAdminConnectionsIdRoute
  '/admin/organizations/$id': typeof AdminAdminOrganizationsIdRoute
  '/admin/runs/$id': typeof AdminAdminRunsIdRoute
  '/app/campaigns/$id': typeof AuthenticatedAppCampaignsIdRoute
  '/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/app/runs/$id': typeof AuthenticatedAppRunsIdRoute
  '/api/oauth/$connector/authorize': typeof ApiOauthConnectorAuthorizeRoute
  '/api/oauth/$connector/callback': typeof ApiOauthConnectorCallbackRoute
  '/api/runs/$id/stream': typeof ApiRunsIdStreamRoute
  '/app/campaigns/': typeof AuthenticatedAppCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/onboarding/accounts': typeof OnboardingAccountsRoute
  '/onboarding/audit': typeof OnboardingAuditRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/budget': typeof OnboardingBudgetRoute
  '/onboarding/business': typeof OnboardingBusinessRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/control': typeof OnboardingControlRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/summary': typeof OnboardingSummaryRoute
  '/plateformes/$slug': typeof PlateformesSlugRoute
  '/secteurs/$slug': typeof SecteursSlugRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/plateformes': typeof PlateformesIndexRoute
  '/secteurs': typeof SecteursIndexRoute
  '/admin/actions': typeof AdminAdminActionsRoute
  '/admin/approvals': typeof AdminAdminApprovalsRoute
  '/admin/audit': typeof AdminAdminAuditRoute
  '/admin/billing': typeof AdminAdminBillingRoute
  '/admin/booking': typeof AdminAdminBookingRoute
  '/admin/compliance': typeof AdminAdminComplianceRoute
  '/admin/connections': typeof AdminAdminConnectionsRouteWithChildren
  '/admin/costs': typeof AdminAdminCostsRoute
  '/admin/finance': typeof AdminAdminFinanceRoute
  '/admin/flags': typeof AdminAdminFlagsRoute
  '/admin/incidents': typeof AdminAdminIncidentsRoute
  '/admin/mcp': typeof AdminAdminMcpRoute
  '/admin/organizations': typeof AdminAdminOrganizationsRouteWithChildren
  '/admin/policies': typeof AdminAdminPoliciesRoute
  '/admin/product-analytics': typeof AdminAdminProductAnalyticsRoute
  '/admin/prompts': typeof AdminAdminPromptsRoute
  '/admin/roles': typeof AdminAdminRolesRoute
  '/admin/runs': typeof AdminAdminRunsRouteWithChildren
  '/admin/security': typeof AdminAdminSecurityRoute
  '/admin/support': typeof AdminAdminSupportRoute
  '/admin/system': typeof AdminAdminSystemRoute
  '/admin/templates': typeof AdminAdminTemplatesRoute
  '/admin/usage': typeof AdminAdminUsageRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/app/agency': typeof AuthenticatedAppAgencyRoute
  '/app/audit': typeof AuthenticatedAppAuditRoute
  '/app/automations': typeof AuthenticatedAppAutomationsRoute
  '/app/connections': typeof AuthenticatedAppConnectionsRoute
  '/app/creations': typeof AuthenticatedAppCreationsRoute
  '/app/leads': typeof AuthenticatedAppLeadsRoute
  '/app/mcp': typeof AuthenticatedAppMcpRoute
  '/app/orkestria': typeof AuthenticatedAppOrkestriaRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/roadmap': typeof AuthenticatedAppRoadmapRoute
  '/app/runs': typeof AuthenticatedAppRunsRouteWithChildren
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/autonomy': typeof ApiCronAutonomyRoute
  '/api/mcp/call': typeof ApiMcpCallRoute
  '/api/mcp/tools': typeof ApiMcpToolsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/publicite/$sector/$city': typeof PubliciteSectorCityRoute
  '/admin': typeof AdminAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/api/mcp': typeof ApiMcpIndexRoute
  '/admin/connections/$id': typeof AdminAdminConnectionsIdRoute
  '/admin/organizations/$id': typeof AdminAdminOrganizationsIdRoute
  '/admin/runs/$id': typeof AdminAdminRunsIdRoute
  '/app/campaigns/$id': typeof AuthenticatedAppCampaignsIdRoute
  '/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/app/runs/$id': typeof AuthenticatedAppRunsIdRoute
  '/api/oauth/$connector/authorize': typeof ApiOauthConnectorAuthorizeRoute
  '/api/oauth/$connector/callback': typeof ApiOauthConnectorCallbackRoute
  '/api/runs/$id/stream': typeof ApiRunsIdStreamRoute
  '/app/campaigns': typeof AuthenticatedAppCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/onboarding/accounts': typeof OnboardingAccountsRoute
  '/onboarding/audit': typeof OnboardingAuditRoute
  '/onboarding/brand': typeof OnboardingBrandRoute
  '/onboarding/budget': typeof OnboardingBudgetRoute
  '/onboarding/business': typeof OnboardingBusinessRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/control': typeof OnboardingControlRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/summary': typeof OnboardingSummaryRoute
  '/plateformes/$slug': typeof PlateformesSlugRoute
  '/secteurs/$slug': typeof SecteursSlugRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/plateformes/': typeof PlateformesIndexRoute
  '/secteurs/': typeof SecteursIndexRoute
  '/_admin/admin/actions': typeof AdminAdminActionsRoute
  '/_admin/admin/approvals': typeof AdminAdminApprovalsRoute
  '/_admin/admin/audit': typeof AdminAdminAuditRoute
  '/_admin/admin/billing': typeof AdminAdminBillingRoute
  '/_admin/admin/booking': typeof AdminAdminBookingRoute
  '/_admin/admin/compliance': typeof AdminAdminComplianceRoute
  '/_admin/admin/connections': typeof AdminAdminConnectionsRouteWithChildren
  '/_admin/admin/costs': typeof AdminAdminCostsRoute
  '/_admin/admin/finance': typeof AdminAdminFinanceRoute
  '/_admin/admin/flags': typeof AdminAdminFlagsRoute
  '/_admin/admin/incidents': typeof AdminAdminIncidentsRoute
  '/_admin/admin/mcp': typeof AdminAdminMcpRoute
  '/_admin/admin/organizations': typeof AdminAdminOrganizationsRouteWithChildren
  '/_admin/admin/policies': typeof AdminAdminPoliciesRoute
  '/_admin/admin/product-analytics': typeof AdminAdminProductAnalyticsRoute
  '/_admin/admin/prompts': typeof AdminAdminPromptsRoute
  '/_admin/admin/roles': typeof AdminAdminRolesRoute
  '/_admin/admin/runs': typeof AdminAdminRunsRouteWithChildren
  '/_admin/admin/security': typeof AdminAdminSecurityRoute
  '/_admin/admin/support': typeof AdminAdminSupportRoute
  '/_admin/admin/system': typeof AdminAdminSystemRoute
  '/_admin/admin/templates': typeof AdminAdminTemplatesRoute
  '/_admin/admin/usage': typeof AdminAdminUsageRoute
  '/_admin/admin/users': typeof AdminAdminUsersRoute
  '/_authenticated/app/agency': typeof AuthenticatedAppAgencyRoute
  '/_authenticated/app/audit': typeof AuthenticatedAppAuditRoute
  '/_authenticated/app/automations': typeof AuthenticatedAppAutomationsRoute
  '/_authenticated/app/campaigns': typeof AuthenticatedAppCampaignsRouteWithChildren
  '/_authenticated/app/connections': typeof AuthenticatedAppConnectionsRoute
  '/_authenticated/app/creations': typeof AuthenticatedAppCreationsRoute
  '/_authenticated/app/leads': typeof AuthenticatedAppLeadsRoute
  '/_authenticated/app/mcp': typeof AuthenticatedAppMcpRoute
  '/_authenticated/app/orkestria': typeof AuthenticatedAppOrkestriaRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/roadmap': typeof AuthenticatedAppRoadmapRoute
  '/_authenticated/app/runs': typeof AuthenticatedAppRunsRouteWithChildren
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/autonomy': typeof ApiCronAutonomyRoute
  '/api/mcp/call': typeof ApiMcpCallRoute
  '/api/mcp/tools': typeof ApiMcpToolsRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/publicite/$sector/$city': typeof PubliciteSectorCityRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/api/mcp/': typeof ApiMcpIndexRoute
  '/_admin/admin/connections/$id': typeof AdminAdminConnectionsIdRoute
  '/_admin/admin/organizations/$id': typeof AdminAdminOrganizationsIdRoute
  '/_admin/admin/runs/$id': typeof AdminAdminRunsIdRoute
  '/_authenticated/app/campaigns/$id': typeof AuthenticatedAppCampaignsIdRoute
  '/_authenticated/app/campaigns/new': typeof AuthenticatedAppCampaignsNewRoute
  '/_authenticated/app/runs/$id': typeof AuthenticatedAppRunsIdRoute
  '/api/oauth/$connector/authorize': typeof ApiOauthConnectorAuthorizeRoute
  '/api/oauth/$connector/callback': typeof ApiOauthConnectorCallbackRoute
  '/api/runs/$id/stream': typeof ApiRunsIdStreamRoute
  '/_authenticated/app/campaigns/': typeof AuthenticatedAppCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/docs'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/setup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/app'
    | '/onboarding/accounts'
    | '/onboarding/audit'
    | '/onboarding/brand'
    | '/onboarding/budget'
    | '/onboarding/business'
    | '/onboarding/connect'
    | '/onboarding/control'
    | '/onboarding/goal'
    | '/onboarding/summary'
    | '/plateformes/$slug'
    | '/secteurs/$slug'
    | '/onboarding/'
    | '/plateformes/'
    | '/secteurs/'
    | '/admin/actions'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/booking'
    | '/admin/compliance'
    | '/admin/connections'
    | '/admin/costs'
    | '/admin/finance'
    | '/admin/flags'
    | '/admin/incidents'
    | '/admin/mcp'
    | '/admin/organizations'
    | '/admin/policies'
    | '/admin/product-analytics'
    | '/admin/prompts'
    | '/admin/roles'
    | '/admin/runs'
    | '/admin/security'
    | '/admin/support'
    | '/admin/system'
    | '/admin/templates'
    | '/admin/usage'
    | '/admin/users'
    | '/app/agency'
    | '/app/audit'
    | '/app/automations'
    | '/app/campaigns'
    | '/app/connections'
    | '/app/creations'
    | '/app/leads'
    | '/app/mcp'
    | '/app/orkestria'
    | '/app/reports'
    | '/app/roadmap'
    | '/app/runs'
    | '/app/settings'
    | '/api/auth/$'
    | '/api/cron/autonomy'
    | '/api/mcp/call'
    | '/api/mcp/tools'
    | '/api/stripe/webhook'
    | '/publicite/$sector/$city'
    | '/admin/'
    | '/app/'
    | '/api/mcp/'
    | '/admin/connections/$id'
    | '/admin/organizations/$id'
    | '/admin/runs/$id'
    | '/app/campaigns/$id'
    | '/app/campaigns/new'
    | '/app/runs/$id'
    | '/api/oauth/$connector/authorize'
    | '/api/oauth/$connector/callback'
    | '/api/runs/$id/stream'
    | '/app/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/docs'
    | '/privacy'
    | '/reset-password'
    | '/setup'
    | '/sitemap.xml'
    | '/terms'
    | '/onboarding/accounts'
    | '/onboarding/audit'
    | '/onboarding/brand'
    | '/onboarding/budget'
    | '/onboarding/business'
    | '/onboarding/connect'
    | '/onboarding/control'
    | '/onboarding/goal'
    | '/onboarding/summary'
    | '/plateformes/$slug'
    | '/secteurs/$slug'
    | '/onboarding'
    | '/plateformes'
    | '/secteurs'
    | '/admin/actions'
    | '/admin/approvals'
    | '/admin/audit'
    | '/admin/billing'
    | '/admin/booking'
    | '/admin/compliance'
    | '/admin/connections'
    | '/admin/costs'
    | '/admin/finance'
    | '/admin/flags'
    | '/admin/incidents'
    | '/admin/mcp'
    | '/admin/organizations'
    | '/admin/policies'
    | '/admin/product-analytics'
    | '/admin/prompts'
    | '/admin/roles'
    | '/admin/runs'
    | '/admin/security'
    | '/admin/support'
    | '/admin/system'
    | '/admin/templates'
    | '/admin/usage'
    | '/admin/users'
    | '/app/agency'
    | '/app/audit'
    | '/app/automations'
    | '/app/connections'
    | '/app/creations'
    | '/app/leads'
    | '/app/mcp'
    | '/app/orkestria'
    | '/app/reports'
    | '/app/roadmap'
    | '/app/runs'
    | '/app/settings'
    | '/api/auth/$'
    | '/api/cron/autonomy'
    | '/api/mcp/call'
    | '/api/mcp/tools'
    | '/api/stripe/webhook'
    | '/publicite/$sector/$city'
    | '/admin'
    | '/app'
    | '/api/mcp'
    | '/admin/connections/$id'
    | '/admin/organizations/$id'
    | '/admin/runs/$id'
    | '/app/campaigns/$id'
    | '/app/campaigns/new'
    | '/app/runs/$id'
    | '/api/oauth/$connector/authorize'
    | '/api/oauth/$connector/callback'
    | '/api/runs/$id/stream'
    | '/app/campaigns'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/docs'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/setup'
    | '/sitemap.xml'
    | '/terms'
    | '/_admin/admin'
    | '/_authenticated/app'
    | '/onboarding/accounts'
    | '/onboarding/audit'
    | '/onboarding/brand'
    | '/onboarding/budget'
    | '/onboarding/business'
    | '/onboarding/connect'
    | '/onboarding/control'
    | '/onboarding/goal'
    | '/onboarding/summary'
    | '/plateformes/$slug'
    | '/secteurs/$slug'
    | '/onboarding/'
    | '/plateformes/'
    | '/secteurs/'
    | '/_admin/admin/actions'
    | '/_admin/admin/approvals'
    | '/_admin/admin/audit'
    | '/_admin/admin/billing'
    | '/_admin/admin/booking'
    | '/_admin/admin/compliance'
    | '/_admin/admin/connections'
    | '/_admin/admin/costs'
    | '/_admin/admin/finance'
    | '/_admin/admin/flags'
    | '/_admin/admin/incidents'
    | '/_admin/admin/mcp'
    | '/_admin/admin/organizations'
    | '/_admin/admin/policies'
    | '/_admin/admin/product-analytics'
    | '/_admin/admin/prompts'
    | '/_admin/admin/roles'
    | '/_admin/admin/runs'
    | '/_admin/admin/security'
    | '/_admin/admin/support'
    | '/_admin/admin/system'
    | '/_admin/admin/templates'
    | '/_admin/admin/usage'
    | '/_admin/admin/users'
    | '/_authenticated/app/agency'
    | '/_authenticated/app/audit'
    | '/_authenticated/app/automations'
    | '/_authenticated/app/campaigns'
    | '/_authenticated/app/connections'
    | '/_authenticated/app/creations'
    | '/_authenticated/app/leads'
    | '/_authenticated/app/mcp'
    | '/_authenticated/app/orkestria'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/roadmap'
    | '/_authenticated/app/runs'
    | '/_authenticated/app/settings'
    | '/api/auth/$'
    | '/api/cron/autonomy'
    | '/api/mcp/call'
    | '/api/mcp/tools'
    | '/api/stripe/webhook'
    | '/publicite/$sector/$city'
    | '/_admin/admin/'
    | '/_authenticated/app/'
    | '/api/mcp/'
    | '/_admin/admin/connections/$id'
    | '/_admin/admin/organizations/$id'
    | '/_admin/admin/runs/$id'
    | '/_authenticated/app/campaigns/$id'
    | '/_authenticated/app/campaigns/new'
    | '/_authenticated/app/runs/$id'
    | '/api/oauth/$connector/authorize'
    | '/api/oauth/$connector/callback'
    | '/api/runs/$id/stream'
    | '/_authenticated/app/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DocsRoute: typeof DocsRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  PlateformesSlugRoute: typeof PlateformesSlugRoute
  SecteursSlugRoute: typeof SecteursSlugRoute
  PlateformesIndexRoute: typeof PlateformesIndexRoute
  SecteursIndexRoute: typeof SecteursIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronAutonomyRoute: typeof ApiCronAutonomyRoute
  ApiMcpCallRoute: typeof ApiMcpCallRoute
  ApiMcpToolsRoute: typeof ApiMcpToolsRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  PubliciteSectorCityRoute: typeof PubliciteSectorCityRoute
  ApiMcpIndexRoute: typeof ApiMcpIndexRoute
  ApiOauthConnectorAuthorizeRoute: typeof ApiOauthConnectorAuthorizeRoute
  ApiOauthConnectorCallbackRoute: typeof ApiOauthConnectorCallbackRoute
  ApiRunsIdStreamRoute: typeof ApiRunsIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/accounts': {
      id: '/onboarding/accounts'
      path: '/accounts'
      fullPath: '/onboarding/accounts'
      preLoaderRoute: typeof OnboardingAccountsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/audit': {
      id: '/onboarding/audit'
      path: '/audit'
      fullPath: '/onboarding/audit'
      preLoaderRoute: typeof OnboardingAuditRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/brand': {
      id: '/onboarding/brand'
      path: '/brand'
      fullPath: '/onboarding/brand'
      preLoaderRoute: typeof OnboardingBrandRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/budget': {
      id: '/onboarding/budget'
      path: '/budget'
      fullPath: '/onboarding/budget'
      preLoaderRoute: typeof OnboardingBudgetRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/business': {
      id: '/onboarding/business'
      path: '/business'
      fullPath: '/onboarding/business'
      preLoaderRoute: typeof OnboardingBusinessRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/connect': {
      id: '/onboarding/connect'
      path: '/connect'
      fullPath: '/onboarding/connect'
      preLoaderRoute: typeof OnboardingConnectRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/control': {
      id: '/onboarding/control'
      path: '/control'
      fullPath: '/onboarding/control'
      preLoaderRoute: typeof OnboardingControlRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/goal': {
      id: '/onboarding/goal'
      path: '/goal'
      fullPath: '/onboarding/goal'
      preLoaderRoute: typeof OnboardingGoalRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/summary': {
      id: '/onboarding/summary'
      path: '/summary'
      fullPath: '/onboarding/summary'
      preLoaderRoute: typeof OnboardingSummaryRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/plateformes/': {
      id: '/plateformes/'
      path: '/plateformes'
      fullPath: '/plateformes/'
      preLoaderRoute: typeof PlateformesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plateformes/$slug': {
      id: '/plateformes/$slug'
      path: '/plateformes/$slug'
      fullPath: '/plateformes/$slug'
      preLoaderRoute: typeof PlateformesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secteurs/': {
      id: '/secteurs/'
      path: '/secteurs'
      fullPath: '/secteurs/'
      preLoaderRoute: typeof SecteursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secteurs/$slug': {
      id: '/secteurs/$slug'
      path: '/secteurs/$slug'
      fullPath: '/secteurs/$slug'
      preLoaderRoute: typeof SecteursSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/actions': {
      id: '/_admin/admin/actions'
      path: '/actions'
      fullPath: '/admin/actions'
      preLoaderRoute: typeof AdminAdminActionsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/approvals': {
      id: '/_admin/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminAdminApprovalsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/audit': {
      id: '/_admin/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAdminAuditRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/billing': {
      id: '/_admin/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminAdminBillingRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/booking': {
      id: '/_admin/admin/booking'
      path: '/booking'
      fullPath: '/admin/booking'
      preLoaderRoute: typeof AdminAdminBookingRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/compliance': {
      id: '/_admin/admin/compliance'
      path: '/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AdminAdminComplianceRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/connections': {
      id: '/_admin/admin/connections'
      path: '/connections'
      fullPath: '/admin/connections'
      preLoaderRoute: typeof AdminAdminConnectionsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/costs': {
      id: '/_admin/admin/costs'
      path: '/costs'
      fullPath: '/admin/costs'
      preLoaderRoute: typeof AdminAdminCostsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/finance': {
      id: '/_admin/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminAdminFinanceRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/flags': {
      id: '/_admin/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminAdminFlagsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/incidents': {
      id: '/_admin/admin/incidents'
      path: '/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AdminAdminIncidentsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/mcp': {
      id: '/_admin/admin/mcp'
      path: '/mcp'
      fullPath: '/admin/mcp'
      preLoaderRoute: typeof AdminAdminMcpRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/organizations': {
      id: '/_admin/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminAdminOrganizationsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/policies': {
      id: '/_admin/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AdminAdminPoliciesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/product-analytics': {
      id: '/_admin/admin/product-analytics'
      path: '/product-analytics'
      fullPath: '/admin/product-analytics'
      preLoaderRoute: typeof AdminAdminProductAnalyticsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/prompts': {
      id: '/_admin/admin/prompts'
      path: '/prompts'
      fullPath: '/admin/prompts'
      preLoaderRoute: typeof AdminAdminPromptsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/roles': {
      id: '/_admin/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminAdminRolesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/runs': {
      id: '/_admin/admin/runs'
      path: '/runs'
      fullPath: '/admin/runs'
      preLoaderRoute: typeof AdminAdminRunsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/security': {
      id: '/_admin/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminAdminSecurityRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/support': {
      id: '/_admin/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminAdminSupportRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/system': {
      id: '/_admin/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminAdminSystemRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/templates': {
      id: '/_admin/admin/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminAdminTemplatesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/usage': {
      id: '/_admin/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AdminAdminUsageRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/users': {
      id: '/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agency': {
      id: '/_authenticated/app/agency'
      path: '/agency'
      fullPath: '/app/agency'
      preLoaderRoute: typeof AuthenticatedAppAgencyRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/audit': {
      id: '/_authenticated/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AuthenticatedAppAuditRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/automations': {
      id: '/_authenticated/app/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AuthenticatedAppAutomationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/campaigns': {
      id: '/_authenticated/app/campaigns'
      path: '/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AuthenticatedAppCampaignsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/connections': {
      id: '/_authenticated/app/connections'
      path: '/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AuthenticatedAppConnectionsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/creations': {
      id: '/_authenticated/app/creations'
      path: '/creations'
      fullPath: '/app/creations'
      preLoaderRoute: typeof AuthenticatedAppCreationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leads': {
      id: '/_authenticated/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AuthenticatedAppLeadsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/mcp': {
      id: '/_authenticated/app/mcp'
      path: '/mcp'
      fullPath: '/app/mcp'
      preLoaderRoute: typeof AuthenticatedAppMcpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/orkestria': {
      id: '/_authenticated/app/orkestria'
      path: '/orkestria'
      fullPath: '/app/orkestria'
      preLoaderRoute: typeof AuthenticatedAppOrkestriaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/roadmap': {
      id: '/_authenticated/app/roadmap'
      path: '/roadmap'
      fullPath: '/app/roadmap'
      preLoaderRoute: typeof AuthenticatedAppRoadmapRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/runs': {
      id: '/_authenticated/app/runs'
      path: '/runs'
      fullPath: '/app/runs'
      preLoaderRoute: typeof AuthenticatedAppRunsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/autonomy': {
      id: '/api/cron/autonomy'
      path: '/api/cron/autonomy'
      fullPath: '/api/cron/autonomy'
      preLoaderRoute: typeof ApiCronAutonomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/': {
      id: '/api/mcp/'
      path: '/api/mcp'
      fullPath: '/api/mcp/'
      preLoaderRoute: typeof ApiMcpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/call': {
      id: '/api/mcp/call'
      path: '/api/mcp/call'
      fullPath: '/api/mcp/call'
      preLoaderRoute: typeof ApiMcpCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp/tools': {
      id: '/api/mcp/tools'
      path: '/api/mcp/tools'
      fullPath: '/api/mcp/tools'
      preLoaderRoute: typeof ApiMcpToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicite/$sector/$city': {
      id: '/publicite/$sector/$city'
      path: '/publicite/$sector/$city'
      fullPath: '/publicite/$sector/$city'
      preLoaderRoute: typeof PubliciteSectorCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/connections/$id': {
      id: '/_admin/admin/connections/$id'
      path: '/$id'
      fullPath: '/admin/connections/$id'
      preLoaderRoute: typeof AdminAdminConnectionsIdRouteImport
      parentRoute: typeof AdminAdminConnectionsRoute
    }
    '/_admin/admin/organizations/$id': {
      id: '/_admin/admin/organizations/$id'
      path: '/$id'
      fullPath: '/admin/organizations/$id'
      preLoaderRoute: typeof AdminAdminOrganizationsIdRouteImport
      parentRoute: typeof AdminAdminOrganizationsRoute
    }
    '/_admin/admin/runs/$id': {
      id: '/_admin/admin/runs/$id'
      path: '/$id'
      fullPath: '/admin/runs/$id'
      preLoaderRoute: typeof AdminAdminRunsIdRouteImport
      parentRoute: typeof AdminAdminRunsRoute
    }
    '/_authenticated/app/campaigns/': {
      id: '/_authenticated/app/campaigns/'
      path: '/'
      fullPath: '/app/campaigns/'
      preLoaderRoute: typeof AuthenticatedAppCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedAppCampaignsRoute
    }
    '/_authenticated/app/campaigns/$id': {
      id: '/_authenticated/app/campaigns/$id'
      path: '/$id'
      fullPath: '/app/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedAppCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedAppCampaignsRoute
    }
    '/_authenticated/app/campaigns/new': {
      id: '/_authenticated/app/campaigns/new'
      path: '/new'
      fullPath: '/app/campaigns/new'
      preLoaderRoute: typeof AuthenticatedAppCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedAppCampaignsRoute
    }
    '/_authenticated/app/runs/$id': {
      id: '/_authenticated/app/runs/$id'
      path: '/$id'
      fullPath: '/app/runs/$id'
      preLoaderRoute: typeof AuthenticatedAppRunsIdRouteImport
      parentRoute: typeof AuthenticatedAppRunsRoute
    }
    '/api/oauth/$connector/authorize': {
      id: '/api/oauth/$connector/authorize'
      path: '/api/oauth/$connector/authorize'
      fullPath: '/api/oauth/$connector/authorize'
      preLoaderRoute: typeof ApiOauthConnectorAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/$connector/callback': {
      id: '/api/oauth/$connector/callback'
      path: '/api/oauth/$connector/callback'
      fullPath: '/api/oauth/$connector/callback'
      preLoaderRoute: typeof ApiOauthConnectorCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runs/$id/stream': {
      id: '/api/runs/$id/stream'
      path: '/api/runs/$id/stream'
      fullPath: '/api/runs/$id/stream'
      preLoaderRoute: typeof ApiRunsIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAdminConnectionsRouteChildren {
  AdminAdminConnectionsIdRoute: typeof AdminAdminConnectionsIdRoute
}

const AdminAdminConnectionsRouteChildren: AdminAdminConnectionsRouteChildren = {
  AdminAdminConnectionsIdRoute: AdminAdminConnectionsIdRoute,
}

const AdminAdminConnectionsRouteWithChildren =
  AdminAdminConnectionsRoute._addFileChildren(
    AdminAdminConnectionsRouteChildren,
  )

interface AdminAdminOrganizationsRouteChildren {
  AdminAdminOrganizationsIdRoute: typeof AdminAdminOrganizationsIdRoute
}

const AdminAdminOrganizationsRouteChildren: AdminAdminOrganizationsRouteChildren =
  {
    AdminAdminOrganizationsIdRoute: AdminAdminOrganizationsIdRoute,
  }

const AdminAdminOrganizationsRouteWithChildren =
  AdminAdminOrganizationsRoute._addFileChildren(
    AdminAdminOrganizationsRouteChildren,
  )

interface AdminAdminRunsRouteChildren {
  AdminAdminRunsIdRoute: typeof AdminAdminRunsIdRoute
}

const AdminAdminRunsRouteChildren: AdminAdminRunsRouteChildren = {
  AdminAdminRunsIdRoute: AdminAdminRunsIdRoute,
}

const AdminAdminRunsRouteWithChildren = AdminAdminRunsRoute._addFileChildren(
  AdminAdminRunsRouteChildren,
)

interface AdminAdminRouteChildren {
  AdminAdminActionsRoute: typeof AdminAdminActionsRoute
  AdminAdminApprovalsRoute: typeof AdminAdminApprovalsRoute
  AdminAdminAuditRoute: typeof AdminAdminAuditRoute
  AdminAdminBillingRoute: typeof AdminAdminBillingRoute
  AdminAdminBookingRoute: typeof AdminAdminBookingRoute
  AdminAdminComplianceRoute: typeof AdminAdminComplianceRoute
  AdminAdminConnectionsRoute: typeof AdminAdminConnectionsRouteWithChildren
  AdminAdminCostsRoute: typeof AdminAdminCostsRoute
  AdminAdminFinanceRoute: typeof AdminAdminFinanceRoute
  AdminAdminFlagsRoute: typeof AdminAdminFlagsRoute
  AdminAdminIncidentsRoute: typeof AdminAdminIncidentsRoute
  AdminAdminMcpRoute: typeof AdminAdminMcpRoute
  AdminAdminOrganizationsRoute: typeof AdminAdminOrganizationsRouteWithChildren
  AdminAdminPoliciesRoute: typeof AdminAdminPoliciesRoute
  AdminAdminProductAnalyticsRoute: typeof AdminAdminProductAnalyticsRoute
  AdminAdminPromptsRoute: typeof AdminAdminPromptsRoute
  AdminAdminRolesRoute: typeof AdminAdminRolesRoute
  AdminAdminRunsRoute: typeof AdminAdminRunsRouteWithChildren
  AdminAdminSecurityRoute: typeof AdminAdminSecurityRoute
  AdminAdminSupportRoute: typeof AdminAdminSupportRoute
  AdminAdminSystemRoute: typeof AdminAdminSystemRoute
  AdminAdminTemplatesRoute: typeof AdminAdminTemplatesRoute
  AdminAdminUsageRoute: typeof AdminAdminUsageRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminActionsRoute: AdminAdminActionsRoute,
  AdminAdminApprovalsRoute: AdminAdminApprovalsRoute,
  AdminAdminAuditRoute: AdminAdminAuditRoute,
  AdminAdminBillingRoute: AdminAdminBillingRoute,
  AdminAdminBookingRoute: AdminAdminBookingRoute,
  AdminAdminComplianceRoute: AdminAdminComplianceRoute,
  AdminAdminConnectionsRoute: AdminAdminConnectionsRouteWithChildren,
  AdminAdminCostsRoute: AdminAdminCostsRoute,
  AdminAdminFinanceRoute: AdminAdminFinanceRoute,
  AdminAdminFlagsRoute: AdminAdminFlagsRoute,
  AdminAdminIncidentsRoute: AdminAdminIncidentsRoute,
  AdminAdminMcpRoute: AdminAdminMcpRoute,
  AdminAdminOrganizationsRoute: AdminAdminOrganizationsRouteWithChildren,
  AdminAdminPoliciesRoute: AdminAdminPoliciesRoute,
  AdminAdminProductAnalyticsRoute: AdminAdminProductAnalyticsRoute,
  AdminAdminPromptsRoute: AdminAdminPromptsRoute,
  AdminAdminRolesRoute: AdminAdminRolesRoute,
  AdminAdminRunsRoute: AdminAdminRunsRouteWithChildren,
  AdminAdminSecurityRoute: AdminAdminSecurityRoute,
  AdminAdminSupportRoute: AdminAdminSupportRoute,
  AdminAdminSystemRoute: AdminAdminSystemRoute,
  AdminAdminTemplatesRoute: AdminAdminTemplatesRoute,
  AdminAdminUsageRoute: AdminAdminUsageRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthenticatedAppCampaignsRouteChildren {
  AuthenticatedAppCampaignsIdRoute: typeof AuthenticatedAppCampaignsIdRoute
  AuthenticatedAppCampaignsNewRoute: typeof AuthenticatedAppCampaignsNewRoute
  AuthenticatedAppCampaignsIndexRoute: typeof AuthenticatedAppCampaignsIndexRoute
}

const AuthenticatedAppCampaignsRouteChildren: AuthenticatedAppCampaignsRouteChildren =
  {
    AuthenticatedAppCampaignsIdRoute: AuthenticatedAppCampaignsIdRoute,
    AuthenticatedAppCampaignsNewRoute: AuthenticatedAppCampaignsNewRoute,
    AuthenticatedAppCampaignsIndexRoute: AuthenticatedAppCampaignsIndexRoute,
  }

const AuthenticatedAppCampaignsRouteWithChildren =
  AuthenticatedAppCampaignsRoute._addFileChildren(
    AuthenticatedAppCampaignsRouteChildren,
  )

interface AuthenticatedAppRunsRouteChildren {
  AuthenticatedAppRunsIdRoute: typeof AuthenticatedAppRunsIdRoute
}

const AuthenticatedAppRunsRouteChildren: AuthenticatedAppRunsRouteChildren = {
  AuthenticatedAppRunsIdRoute: AuthenticatedAppRunsIdRoute,
}

const AuthenticatedAppRunsRouteWithChildren =
  AuthenticatedAppRunsRoute._addFileChildren(AuthenticatedAppRunsRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgencyRoute: typeof AuthenticatedAppAgencyRoute
  AuthenticatedAppAuditRoute: typeof AuthenticatedAppAuditRoute
  AuthenticatedAppAutomationsRoute: typeof AuthenticatedAppAutomationsRoute
  AuthenticatedAppCampaignsRoute: typeof AuthenticatedAppCampaignsRouteWithChildren
  AuthenticatedAppConnectionsRoute: typeof AuthenticatedAppConnectionsRoute
  AuthenticatedAppCreationsRoute: typeof AuthenticatedAppCreationsRoute
  AuthenticatedAppLeadsRoute: typeof AuthenticatedAppLeadsRoute
  AuthenticatedAppMcpRoute: typeof AuthenticatedAppMcpRoute
  AuthenticatedAppOrkestriaRoute: typeof AuthenticatedAppOrkestriaRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppRoadmapRoute: typeof AuthenticatedAppRoadmapRoute
  AuthenticatedAppRunsRoute: typeof AuthenticatedAppRunsRouteWithChildren
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgencyRoute: AuthenticatedAppAgencyRoute,
  AuthenticatedAppAuditRoute: AuthenticatedAppAuditRoute,
  AuthenticatedAppAutomationsRoute: AuthenticatedAppAutomationsRoute,
  AuthenticatedAppCampaignsRoute: AuthenticatedAppCampaignsRouteWithChildren,
  AuthenticatedAppConnectionsRoute: AuthenticatedAppConnectionsRoute,
  AuthenticatedAppCreationsRoute: AuthenticatedAppCreationsRoute,
  AuthenticatedAppLeadsRoute: AuthenticatedAppLeadsRoute,
  AuthenticatedAppMcpRoute: AuthenticatedAppMcpRoute,
  AuthenticatedAppOrkestriaRoute: AuthenticatedAppOrkestriaRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppRoadmapRoute: AuthenticatedAppRoadmapRoute,
  AuthenticatedAppRunsRoute: AuthenticatedAppRunsRouteWithChildren,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingAccountsRoute: typeof OnboardingAccountsRoute
  OnboardingAuditRoute: typeof OnboardingAuditRoute
  OnboardingBrandRoute: typeof OnboardingBrandRoute
  OnboardingBudgetRoute: typeof OnboardingBudgetRoute
  OnboardingBusinessRoute: typeof OnboardingBusinessRoute
  OnboardingConnectRoute: typeof OnboardingConnectRoute
  OnboardingControlRoute: typeof OnboardingControlRoute
  OnboardingGoalRoute: typeof OnboardingGoalRoute
  OnboardingSummaryRoute: typeof OnboardingSummaryRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingAccountsRoute: OnboardingAccountsRoute,
  OnboardingAuditRoute: OnboardingAuditRoute,
  OnboardingBrandRoute: OnboardingBrandRoute,
  OnboardingBudgetRoute: OnboardingBudgetRoute,
  OnboardingBusinessRoute: OnboardingBusinessRoute,
  OnboardingConnectRoute: OnboardingConnectRoute,
  OnboardingControlRoute: OnboardingControlRoute,
  OnboardingGoalRoute: OnboardingGoalRoute,
  OnboardingSummaryRoute: OnboardingSummaryRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DocsRoute: DocsRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  PlateformesSlugRoute: PlateformesSlugRoute,
  SecteursSlugRoute: SecteursSlugRoute,
  PlateformesIndexRoute: PlateformesIndexRoute,
  SecteursIndexRoute: SecteursIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronAutonomyRoute: ApiCronAutonomyRoute,
  ApiMcpCallRoute: ApiMcpCallRoute,
  ApiMcpToolsRoute: ApiMcpToolsRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  PubliciteSectorCityRoute: PubliciteSectorCityRoute,
  ApiMcpIndexRoute: ApiMcpIndexRoute,
  ApiOauthConnectorAuthorizeRoute: ApiOauthConnectorAuthorizeRoute,
  ApiOauthConnectorCallbackRoute: ApiOauthConnectorCallbackRoute,
  ApiRunsIdStreamRoute: ApiRunsIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
